CREATE TABLE `p03_prescription_results` (
	`id` text PRIMARY KEY NOT NULL,
	`diagnostic_id` text NOT NULL,
	`analysis_run_id` text NOT NULL,
	`money_now_selection_id` text NOT NULL,
	`money_now_selection_hash` text NOT NULL,
	`p01_analysis_result_id` text NOT NULL,
	`p01_result_hash` text NOT NULL,
	`stage_version` text NOT NULL,
	`prompt_version` text NOT NULL,
	`output_schema_version` text NOT NULL,
	`rule_versions_json` text NOT NULL,
	`context_hash` text,
	`input_hash` text NOT NULL,
	`deterministic_input_hash` text NOT NULL,
	`context_json` text,
	`selected_scenario_json` text,
	`backend_metrics_json` text NOT NULL,
	`backend_revenue_scenario_json` text,
	`locked_teaser_version` text NOT NULL,
	`locked_teaser` text NOT NULL,
	`result_json` text,
	`skipped_outcome_json` text,
	`provider_raw_response_json` text,
	`provider` text,
	`model` text,
	`started_at` text NOT NULL,
	`finished_at` text NOT NULL,
	`latency_ms` integer NOT NULL,
	`input_tokens` integer,
	`output_tokens` integer,
	`total_tokens` integer,
	`cost_usd` real,
	`retry_count` integer NOT NULL,
	`technical_retry_count` integer NOT NULL,
	`reevaluation_retry_count` integer NOT NULL,
	`failure_code` text,
	`failure_message` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`diagnostic_id`) REFERENCES `diagnostics`(`id`) ON UPDATE cascade ON DELETE restrict,
	FOREIGN KEY (`analysis_run_id`) REFERENCES `analysis_runs`(`id`) ON UPDATE cascade ON DELETE restrict,
	FOREIGN KEY (`money_now_selection_id`) REFERENCES `money_now_selections`(`id`) ON UPDATE cascade ON DELETE restrict,
	FOREIGN KEY (`p01_analysis_result_id`) REFERENCES `p01_analysis_results`(`id`) ON UPDATE cascade ON DELETE restrict
);
--> statement-breakpoint
CREATE UNIQUE INDEX `p03_prescription_results_run_unique` ON `p03_prescription_results` (`analysis_run_id`);--> statement-breakpoint
CREATE INDEX `p03_prescription_results_selection_idx` ON `p03_prescription_results` (`money_now_selection_id`);--> statement-breakpoint
CREATE INDEX `p03_prescription_results_p01_idx` ON `p03_prescription_results` (`p01_analysis_result_id`);--> statement-breakpoint
CREATE INDEX `p03_prescription_results_input_hash_idx` ON `p03_prescription_results` (`deterministic_input_hash`);